### ISSUE TITLE
Date difference is incorrect when moving between dates

### ISSUE THREAD

**Issue by hyperjeff** [oz/tz#39]
Neat time tool! A hopefully helpful bug report: When launching tz, it will correctly note a date difference (or lack thereof) between different time zones, but when you use arrow keys to move to other times, it will still maintain the date difference established on launch for all other times, even when it should change. See video, which compares US/Central to US/Eastern time zones. Comparing with US/Pacific shows correctly that there is not currently a date difference, but then continues to claim there is never a date difference at any hour.

https://user-images.githubusercontent.com/64038/226516850-e9940b8f-00b4-40fe-a0a3-eea5c8fc7afc.mov

**Comment by oz** [comment]
@hyperjeff thanks for filing an issue, with a video. :)

If I understand correctly, the issue here is that the date shown next to the time zone becomes incorrect when changing date: when you move forward from Mon 20 (CDT) to Tue 21 CDT), the EDT date should stick to Tue 21 and not jump to Wed 22.

Is that right?

**Comment by hyperjeff** [comment]
Yes, that's correct. In general, any time one of the time zones crosses a date barrier (23 ←→ 0) either way, it should re-evaluate the date for that time zone.
